import type { AnalysisSummary } from '../models/types';

const MAX_CELL_LENGTH = 4_000;

function cell(value: string): string {
  const escaped = value
    .replace(/&/gu, '&amp;')
    .replace(/</gu, '&lt;')
    .replace(/>/gu, '&gt;')
    .replace(/@/gu, '&#64;')
    .replace(/\|/gu, '\\|')
    .replace(/\r?\n/gu, ' ');
  return escaped.length > MAX_CELL_LENGTH ? `${escaped.slice(0, MAX_CELL_LENGTH - 1)}…` : escaped;
}

function status(passed: boolean, warning: boolean): string {
  if (warning) return '⚠️ Warning';
  return passed ? '✅ Passed' : '❌ Failed';
}

function coverageDetails(summary: AnalysisSummary): string {
  const result = summary.coverage;
  if (result.coverage === undefined) return result.message;
  return `${result.coverage}%, required ${result.minimum}%${result.reportPath ? ` (${result.reportPath})` : ''}`;
}

export function buildComment(summary: AnalysisSummary, marker: string): string {
  const resultLabel =
    summary.risk.level === 'low'
      ? '✅ Passed'
      : summary.risk.level === 'medium'
        ? '⚠️ Needs attention'
        : '❌ High risk';
  const recommendation =
    summary.risk.level === 'low'
      ? 'This PR looks safe from the configured quality checks.'
      : summary.risk.level === 'medium'
        ? 'Please review the warnings before merging.'
        : 'This PR should not be merged until the failed checks are fixed.';

  const rows = [
    ['PR title', status(summary.title.passed, summary.title.warning), summary.title.actual],
    [
      'Linked issue',
      status(summary.linkedIssue.passed, summary.linkedIssue.warning),
      summary.linkedIssue.matchedReference ?? summary.linkedIssue.message,
    ],
    [
      'Coverage',
      status(summary.coverage.passed, summary.coverage.warning),
      coverageDetails(summary),
    ],
    [
      'Change size',
      status(summary.changeSize.passed, summary.changeSize.warning),
      summary.changeSize.message,
    ],
    ['TODO/FIXME', status(summary.todo.passed, summary.todo.warning), summary.todo.message],
  ];
  const table = rows.map((row) => `| ${row.map((value) => cell(value)).join(' | ')} |`).join('\n');

  return `${marker}

## PR Quality Bot Report

Overall result: ${resultLabel}

Risk score: ${summary.risk.score} / 100

Risk level: ${summary.risk.level[0]?.toUpperCase()}${summary.risk.level.slice(1)}

### Checks

| Check | Result | Details |
|---|---:|---|
${table}

### Recommendation

${recommendation}

---
Generated by PR Quality Bot.`;
}
